apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${{ secrets.DOCKER_USERNAME }}/backend-image:latest  # Ensure the ":latest" tag is specified
          imagePullPolicy: IfNotPresent   # Prevents re-pulling from Docker Hub if the image is already loaded in Minikube
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
