name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adoptopenjdk'  # Ensure this is set explicitly

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          podman build -t backend-image .

      - name: Push Docker image
        run: |
          podman push backend-image

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-ingress.yaml
