name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # 2. Set up JDK 17 using Temurin distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Build the backend project with Maven
      - name: Build with Maven
        run: |
          mvn clean install
        working-directory: "."

      # 4. Build Docker image using Podman
      - name: Build Docker image with Podman
        run: |
          podman build -t backend-image:latest .
        working-directory: "."

      # 5. Load image into Minikube
      - name: Load Image into Minikube
        run: |
          minikube image load backend-image:latest  # Required for Minikube with Podman
      # 6. Set up Kubernetes credentials using kubeconfig
      - name: Set up Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
      # 7. Deploy to Kubernetes (Minikube)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-ingress.yaml
